//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSalon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> FurnitureId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostDelivery { get; set; }
        public Nullable<decimal> CostInstall { get; set; }
        public Nullable<decimal> Sale { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> DateSell { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Furniture Furniture { get; set; }
    }
}
