//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSalon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeFurnitureId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual TypeFurniture TypeFurniture { get; set; }
    }
}
